# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--line-length=88", "--check", "--diff", "--force-exclude=migrations", "src/"]
#        args: ["--line-length=88", "--force-exclude=migrations", "src/"]
        types: [python]
        entry: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        additional_dependencies: ["flake8-django==0.0.4", "pylint-django==2.0.11"]
        types: [python]
        args: ["--max-complexity=30", "--max-line-length=88", "--ignore=DJ01,DJ08,W503,ANN101", "--exclude=docs/*", "src/", "setup.py"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--multi-line=3", "--lbt=1", "--trailing-comma", "--force-grid-wrap=0", "--use-parentheses", "--ensure-newline-before-comments", "--line-length=88"]
  - repo: local
    hooks:
      - id: python-check-pdb
        name: check pdb
        description: 'PDB check inside code'
        entry: '^\s?[^#]+\.set_trace\(\)'
        language: pygrep
        types: [python]
  - repo: https://github.com/collective/zpretty
    rev: 2.4.1
    hooks:
      - id: zpretty
        name: zpretty
  - repo: https://github.com/regebro/pyroma
    rev: "3.2"
    hooks:
      - id: pyroma
